services:
  - type: web
    name: gatekeepersbot
    env: python
    plan: starter
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn gatekeepers_album_maker:app --bind 0.0.0.0:$PORT
    envVars:
      - key: BOT_TOKEN
        value: "<YOUR_BOT_TOKEN>"
      - key: OTHER_ENV_VAR
        value: "<VALUE_IF_ANY>"
    autoDeploy: true
    healthCheckPath: /
